### ISSUE TITLE
TODO:

### ISSUE THREAD

**Issue by edshen17** [edshen17/mentalMath2#1]
- [x] Game over
- [x] Blur button/ unblur button
- [x]  Break number / repeat button
- [x]  More tests for functions
- [x] Fix error when pressing R after game finishes
- [x] Add a scale function for speak (shorter/longer pauses for easier/harder questions)
- [x] Log in/ profile pages
- [x] Keep track of user scores  (using mongodb)
- [x] Scoreboard for top scorers 
- [x] CSS
- [x] README
- [ ] Host the game online
